version: '3.7'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: task-db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db/task-db
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "80:8080"
    env_file:
      - .env

volumes:
  db-data:

