name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build frontend
      run: |
        npm install
        npm run build
        mkdir -p ../backend/src/main/resources/static
        cp -r build/* ../backend/src/main/resources/static/
      working-directory: ./frontend

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
          
    - name: Set permission to exec gradlew
      run: chmod +x gradlew
      working-directory: ./backend

    - name: Build backend with Gradle
      run: ./gradlew build
      working-directory: ./backend

    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: l4rma/micronaut
        tags: $(git rev-parse --short HEAD), latests
        dockerfile: ./backend/Dockerfile
        directory: backend/
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: 22
        script: |
          echo "Hello, world!"
          docker stop *
          docker-compose rm -f
          docker-compose build --pull --no-cache
          docker-compose up -d
